# Generated by Django 3.1.7 on 2022-05-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20211102_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user1',
            name='account_num',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='another_referral',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='ifsc',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='referral',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='security',
        ),
        migrations.AddField(
            model_name='bot',
            name='bot_id',
            field=models.IntegerField(default=0),
        ),
    ]
