# Generated by Django 3.1.7 on 2022-05-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20220516_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot3',
            old_name='angel_API_keys',
            new_name='binance_API_keys',
        ),
        migrations.RenameField(
            model_name='bot3',
            old_name='password',
            new_name='binance_Secret_Keys',
        ),
        migrations.RenameField(
            model_name='bot4',
            old_name='angel_API_keys',
            new_name='binance_API_keys',
        ),
        migrations.RenameField(
            model_name='bot4',
            old_name='password',
            new_name='binance_Secret_Keys',
        ),
        migrations.RemoveField(
            model_name='bot3',
            name='username',
        ),
        migrations.RemoveField(
            model_name='bot4',
            name='username',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='angel_API_keys',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='angel_password',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='angel_username',
        ),
    ]
